SELECT * FROM EMPLOYEES 
WHERE EMPLOYEE_ID>=100 AND EMPLOYEE_ID <=105;

SELECT * FROM EMPLOYEES 
WHERE EMPLOYEE_ID in(151 , 152, 153, 154 , 155);

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE 'P%' OR FIRST_NAME  like 'p%';

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%A' OR FIRST_NAME  like '%a';

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%A%' OR FIRST_NAME  like '%a%';

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '__e%' OR FIRST_NAME  like '__E%';

SELECT * FROM EMPLOYEES 
WHERE MANAGER_ID IS NULL ;

SELECT * FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT  NULL ;

INSERT INTO EMPLOYEES values(200,'ahmed','mohmaed','sddfdf',522664,,'djhfjjk',15000,,,,60);

SELECT * FROM EMPLOYEES 
WHERE JOB_ID ='AD_VP' OR JOB_ID ='IT_PROG';

SELECT * FROM EMPLOYEES 
ORDER BY LAST_NAME; 

SELECT * FROM EMPLOYEES 
ORDER BY HIRE_DATE desc;

SELECT * FROM EMPLOYEES 
ORDER BY DEPARTMENT_ID ,salary desc;

SELECT LOWER(LAST_name) FROM EMPLOYEES ;

SELECT upper(FIRST_NAME ) FROM EMPLOYEES ;

SELECT INITCAP(CONCAT(first_name||' ' ,last_name)) FROM EMPLOYEES ;

SELECT * FROM EMPLOYEES 
WHERE LOWER(LAST_NAME )='smith';


